#!/usr/bin/env python3
"""Step 091 -- inner-perturber ('Planet Y') ladder: required mass at
a = 100-200 AU vs the ephemeris bound
====================================================================

Siraj, Chyba & Tremaine (2025) showed that the distant-belt mean-plane
warp cannot be generated by either published distant-planet
realization and would instead require a THIRD body -- 'Planet Y' --
of roughly Mercury-to-Earth mass (0.06-1 M_earth) at a = 100-200 AU
with i >~ 10 deg.  Steps 083/087 measured the required point mass for
distant rungs (a9 = 250-1000 AU) on the cometary boundary-rotation
channel; this step extends the ladder INWARD into the Planet-Y regime
and asks two questions:

  (i)  Can an inner perturber in the SCT25 parameter range produce
       the observed boundary rotation delta theta at all?  The
       required mass is measured on the same CODE class-1 sample with
       the same IAS15/DE440s machinery and the linear mass scaling
       verified in step 083.

  (ii) Is that required mass compatible with the planetary-ephemeris
       bound?  Gomes, Murray, Gomes, Holman & Bernstein (2023, PSJ
       4:66) forecast a median tidal-field uncertainty
           sigma_M = 0.22 M_earth (d/400 AU)^3
       from Juno/Cassini/Mars ranging; the 5-sigma detection line
       1.1 M_earth (d/400 AU)^3 is the boundary above which an inner
       perturber should already appear in the ephemerides.

Two perturber geometries are integrated per rung:

  'anti-aligned' -- the BB21 shepherding orientation continued inward
     (e9=0.30, i9=15.6 deg, varpi9=246.7 deg, Om9=96.9 deg), so the
     100-200 AU rungs join continuously onto the step-087 ladder.

  'warp-plane' -- a perturber sharing the measured warp plane
     (i9=15 deg, Om9=120 deg; step 090 / SCT25), with varpi9=229 deg
     antipodal to the lambda=49 deg boundary axis -- the orientation
     that leans the disk toward the observed cap.

Rungs: a9 = 100, 125, 150, 175, 200, 250 AU.  Deliverables per rung
and geometry: the injected rotation under 6.9 M_earth, the required-
mass distribution in/out of the theta<60 deg cap, and the margin
against the SCT25 Planet-Y box and the Gomes+23 5-sigma ephemeris
line.

Outputs
-------
results/step_b56_inner_perturber.json
results/step_b56_inner_perturber.csv   (per-comet ladder)
results/figures/supplementary/step_b56_inner_perturber.png
"""

import sys as _sys
from pathlib import Path as _Path
_sys.path.insert(0, str(_Path(__file__).resolve().parent.parent.parent))
from scripts.utils.step_logger import StepLogger
from scripts.utils.tep9_common import DATA_RAW, RESULTS, tee_stdout
logger = StepLogger("step_091_inner_perturber")
tee_stdout(logger)
logger.header("Inner-perturber (Planet-Y) ladder vs ephemeris bound (REBOUND/DE440s)")

import csv
import json
import math
import re
import numpy as np
from html.parser import HTMLParser

import rebound
import spiceypy as sp

# ------------------------------------------------------------------
# CODE table parser (identical to step_062/083/087)
# ------------------------------------------------------------------

class TP(HTMLParser):
    def __init__(self):
        super().__init__(); self.rows = []; self.cur = []; self.buf = ""; self.in_td = False
    def handle_starttag(self, t, a):
        if t == "tr": self.cur = []
        elif t == "td": self.in_td = True; self.buf = ""
    def handle_endtag(self, t):
        if t == "td": self.in_td = False; self.cur.append(self.buf.strip())
        elif t == "tr" and self.cur: self.rows.append(self.cur)
    def handle_data(self, d):
        if self.in_td: self.buf += d

def parse_code(path):
    p = TP(); p.feed(open(path, encoding="utf-8", errors="replace").read())
    out = {}
    for r in p.rows:
        if len(r) < 14: continue
        try:
            out[r[0].strip()] = dict(desig=r[0].strip(),
                cls=re.sub(r"^\d", "", r[3].strip()),
                T=r[7].strip(),
                q=float(r[8]), e=float(r[9]), w=float(r[10]),
                Om=float(r[11]), i=float(r[12]), aa=float(r[13]))
        except (ValueError, IndexError):
            continue
    return out

def perih_dir(om, Om, inc):
    co, so, cO, sO, ci, si = np.cos(om), np.sin(om), np.cos(Om), np.sin(Om), np.cos(inc), np.sin(inc)
    return np.array([cO*co - sO*so*ci, sO*co + cO*so*ci, so*si])

def sep(a, b):
    return math.degrees(math.acos(np.clip(np.dot(a, b), -1, 1)))

def lv(l, b):
    l, b = math.radians(l), math.radians(b)
    return np.array([math.cos(b)*math.cos(l), math.cos(b)*math.sin(l), math.sin(b)])

TNO = lv(34, -13)   # transit-axis convention (Phase-3 steps)

# ------------------------------------------------------------------
# Ephemeris setup (identical to step_062/083/087)
# ------------------------------------------------------------------

SPK = DATA_RAW / "spice" / "de440s.bsp"
if not SPK.exists():
    raise FileNotFoundError(f"JPL ephemeris missing: {SPK}")
sp.furnsh(str(SPK))

AU_KM   = 149597870.7
DAY_YR  = 365.25
EPS     = math.radians(23.4392911)
RX      = np.array([[1, 0, 0],
                    [0, math.cos(EPS), math.sin(EPS)],
                    [0, -math.sin(EPS), math.cos(EPS)]])

GM_SUN = 1.32712440018e11
GM = {"1": 2.2031868551e4, "2": 3.2485859200e5, "3": 4.0350323562e5,
      "4": 4.2828375814e4, "5": 1.2671276480e8, "6": 3.7940626000e7,
      "7": 5.7945490100e6, "8": 6.8365271006e6, "9": 1.0868657e3}
PLANET_IDS = list(GM.keys())

def jd_tt(y, m, d):
    if m <= 2: y -= 1; m += 12
    A = y // 100; B = 2 - A + A // 4
    return int(365.25 * (y + 4716)) + int(30.6001 * (m + 1)) + d + B - 1524.5

def perihelion_et(T):
    m = re.match(r"(\d{4})\s+(\d{1,2})\s+(\d+\.?\d*)", T)
    if not m:
        return None
    return (jd_tt(int(m.group(1)), int(m.group(2)), float(m.group(3))) - 2451545.0) * 86400.0

def body_state(body, et):
    st, _ = sp.spkezr(body, et, "J2000", "NONE", "0")
    return RX @ np.array(st[:3]) / AU_KM, RX @ np.array(st[3:]) / AU_KM * 86400 * DAY_YR

# ------------------------------------------------------------------
# Inner-perturber rungs
# ------------------------------------------------------------------

M_EARTH_SUN = 3.0035e-6
M9_EARTH = 6.9
A9_LADDER = [100.0, 125.0, 150.0, 175.0, 200.0, 250.0]
GEOMS = {
    "anti-aligned": dict(e9=0.30, i9=15.6, varpi9=246.7, Om9=96.9),
    "warp-plane":   dict(e9=0.30, i9=15.0, varpi9=229.0, Om9=120.0),
}
M9_USE = 180.0

MU = 4 * math.pi ** 2
R_STOP = 255.0
T_MAX  = -20000.0
DT_OUT = 1.0
# Close-encounter exit: any comet driven inside 0.001 AU of a massive
# body is inside its Roche zone / near surface and is destroyed --
# IAS15's adaptive step otherwise collapses and the call never
# returns.  The threshold is collision scale, not encounter scale:
# real catalogue trajectories (e.g. C/1902 R1's documented 0.049 AU
# Mercury pass) integrate through unaffected.
R_MIN_ENC = 0.001
# Timestep-collapse guard: if IAS15's adaptive step shrinks below ~0.3 s
# the trajectory is numerically degenerate even without a registered
# encounter -- abandon the integration rather than spin.  Real deep-
# encounter transients (e.g. a 0.05 AU Mercury pass) stay above this.
DT_MIN_YR = 1e-8

def p9_state(a9, geo, m9_deg, et):
    w9 = geo["varpi9"] - geo["Om9"]
    P9_yr = a9 ** 1.5
    et_yr = et / (86400.0 * DAY_YR)
    M_at_et = math.radians(m9_deg) + (2 * math.pi / P9_yr) * et_yr
    sim = rebound.Simulation(); sim.G = MU
    sim.add(m=1.0)
    sim.add(a=a9, e=geo["e9"], inc=math.radians(geo["i9"]),
            Omega=math.radians(geo["Om9"]), omega=math.radians(w9),
            M=M_at_et, m=M9_EARTH * M_EARTH_SUN)
    p = sim.particles[1]
    return (np.array([p.x, p.y, p.z]), np.array([p.vx, p.vy, p.vz]))

def init_sim(et):
    sim = rebound.Simulation()
    sim.G = MU
    ps, vs = body_state("10", et)
    sim.add(x=ps[0], y=ps[1], z=ps[2], vx=vs[0], vy=vs[1], vz=vs[2], m=1.0)
    for b in PLANET_IDS:
        pp, vv = body_state(b, et)
        sim.add(x=pp[0], y=pp[1], z=pp[2], vx=vv[0], vy=vv[1], vz=vv[2],
                m=GM[b] / GM_SUN)
    return sim, ps, vs

def state_at_periapsis(ro):
    w_, O_, i_ = map(math.radians, (ro["w"], ro["Om"], ro["i"]))
    ph = perih_dir(w_, O_, i_)
    hh = np.array([math.sin(i_) * math.sin(O_), -math.sin(i_) * math.cos(O_), math.cos(i_)])
    th = np.cross(hh, ph); th /= np.linalg.norm(th)
    rvec = ro["q"] * ph
    vvec = math.sqrt(MU * (1 + ro["e"]) / ro["q"]) * th
    return rvec, vvec

def boundary_orbit(r_rel, v_rel, mtot):
    mu = MU * mtot
    r = np.linalg.norm(r_rel)
    h = np.cross(r_rel, v_rel)
    evec = (np.cross(v_rel, h) / mu) - r_rel / r
    en = np.linalg.norm(evec)
    phat = evec / en if en > 1e-12 else r_rel / r
    E = v_rel.dot(v_rel) / 2 - mu / r
    aa = -2 * E / mu * 1e6
    return phat, aa

def integrate(ro, et, p9=None):
    sim, ps, vs = init_sim(et)
    if p9 is not None:
        sim.add(x=p9[0][0], y=p9[0][1], z=p9[0][2],
                vx=p9[1][0], vy=p9[1][1], vz=p9[1][2], m=p9[2])
    rvec, vvec = state_at_periapsis(ro)
    sim.add(x=rvec[0] + ps[0], y=rvec[1] + ps[1], z=rvec[2] + ps[2],
            vx=vvec[0] + vs[0], vy=vvec[1] + vs[1], vz=vvec[2] + vs[2])
    nc = sim.N - 1
    sim.integrator = "ias15"
    sim.exit_min_distance = R_MIN_ENC
    t = -DT_OUT
    # t is negative for the backward leg; compare elapsed time, not signed t.
    while abs(t) < abs(T_MAX):
        try:
            sim.integrate(t, exact_finish_time=0)
        except rebound.Encounter:
            return None
        if abs(sim.dt) < DT_MIN_YR:
            return None
        p = sim.particles
        r_rel = np.array([p[nc].x - p[0].x, p[nc].y - p[0].y, p[nc].z - p[0].z])
        if np.linalg.norm(r_rel) >= R_STOP:
            break
        t -= DT_OUT
    else:
        return None
    mtot = sum(pp.m for pp in sim.particles)
    p = sim.particles
    r_rel = np.array([p[nc].x - p[0].x, p[nc].y - p[0].y, p[nc].z - p[0].z])
    v_rel = np.array([p[nc].vx - p[0].vx, p[nc].vy - p[0].vy, p[nc].vz - p[0].vz])
    phat, aa_out = boundary_orbit(r_rel, v_rel, mtot)
    return dict(phat=phat, aa_out=aa_out)

# ------------------------------------------------------------------
# Sample: identical selection to step_062/083/087
# ------------------------------------------------------------------

osc  = parse_code(str(DATA_RAW / "code" / "code_osculating.html"))
orig = parse_code(str(DATA_RAW / "code" / "code_original.html"))
fut  = parse_code(str(DATA_RAW / "code" / "code_future.html"))
warsaw = {l[5:17].strip() for l in open(str(DATA_RAW / "warsaw" / "warsaw_tablec.dat")) if len(l) > 115}

sample = []
for k, ro in orig.items():
    if k not in fut: continue
    if not (0 < ro["aa"] < 100 and ro["cls"] in ("1a", "1a+", "1b")) or k in warsaw:
        continue
    if k not in osc: continue
    et = perihelion_et(osc[k]["T"])
    if et is None: continue
    sample.append((k, ro, osc[k], et))

logger.info(f"sample: {len(sample)} class-1 CODE comets")

# ------------------------------------------------------------------
# Integrate: baseline + each rung x geometry per comet
# ------------------------------------------------------------------

def _work_comet(job):
    """Baseline + rung x geometry integrations for one comet."""
    k, ro, oo, et = job
    try:
        return _run_comet(k, ro, oo, et)
    except Exception as e:
        return ("__error__", k, str(e))


def _run_comet(k, ro, oo, et):
    base = integrate(oo, et, None)
    if base is None:
        return None
    po = perih_dir(math.radians(ro["w"]), math.radians(ro["Om"]), math.radians(ro["i"]))
    pf = perih_dir(math.radians(fut[k]["w"]), math.radians(fut[k]["Om"]), math.radians(fut[k]["i"]))
    rec = dict(desig=k, q=ro["q"], cls=ro["cls"],
               theta=sep(-po, TNO), d_of=sep(-po, -pf))
    for gname, geo in GEOMS.items():
        gt = gname.split("-")[0]          # 'anti' / 'warp' column tag
        for a9 in A9_LADDER:
            key = f"{gt}_a{int(a9)}"
            ps9, vs9 = p9_state(a9, geo, M9_USE, et)
            try:
                rp = integrate(oo, et, (ps9, vs9, M9_EARTH * M_EARTH_SUN))
            except Exception:
                rp = None
            rec[f"{key}_drot"] = sep(base["phat"], rp["phat"]) if rp else float("nan")
            rec[f"{key}_mreq"] = (M9_EARTH * rec["d_of"] / rec[f"{key}_drot"]
                                  if np.isfinite(rec[f"{key}_drot"]) and rec[f"{key}_drot"] > 0
                                  else float("nan"))
    return rec


from scripts.utils.parallel import default_workers as _default_workers

if "--workers" in _sys.argv:
    N_WORK = max(1, int(_sys.argv[_sys.argv.index("--workers") + 1]))
else:
    N_WORK = _default_workers()

if N_WORK > 1 and len(sample) > 1:
    import multiprocessing as mp
    ctx = mp.get_context("fork") if _sys.platform != "win32" \
        else mp.get_context("spawn")

    def _init():
        # forked children inherit the parent's BSP fd; concurrent spkezr
        # reads through a shared descriptor corrupt each other -- reopen
        # the kernel so each worker holds its own file handle.
        sp.kclear()
        sp.furnsh(str(SPK))

    with ctx.Pool(min(N_WORK, len(sample)), initializer=_init) as pool:
        recs = pool.map(_work_comet, sample)
else:
    recs = [_work_comet(s) for s in sample]

rows = []
failed = []
for s, rec in zip(sample, recs):
    if rec is None:
        failed.append(s[0])
    elif isinstance(rec, tuple) and rec[0] == "__error__":
        failed.append(rec[1]); logger.warning(f"{rec[1]}: {rec[2]}")
    else:
        rows.append(rec)

logger.info(f"integrated {len(rows)} comets x "
            f"{1 + len(A9_LADDER) * len(GEOMS)} runs; {len(failed)} failed")

# ------------------------------------------------------------------
# Required mass vs distance vs bounds
# ------------------------------------------------------------------

inc = np.array([r["theta"] < 60 for r in rows])

def eph_bound_5sig(d_au):
    """Gomes+23 median tidal uncertainty sigma_M = 0.22 M_earth
    (d/400 AU)^3; the 5-sigma detection line."""
    return 1.1 * (d_au / 400.0) ** 3

res = {"meta": {
    "n": len(rows), "n_failed": len(failed), "failed": failed,
    "geometries": {g: dict(GEOMS[g], M9_deg=M9_USE)
                   for g in GEOMS},
    "a9_ladder_AU": A9_LADDER,
    "anchor_scaling": "alpha = 1.00 measured on the mass ladder "
                      "(step 083) -- m_req(a9) = 6.9*d_of/drot_6.9(a9)",
    "integrator": "ias15", "boundary_AU": R_STOP,
    "ephemeris": "data/raw/spice/de440s.bsp (provenance pinned)",
    "eph_bound": "5-sigma tidal detection line, sigma_M = 0.22 "
                 "M_earth (d/400 AU)^3 (Gomes, Murray, Gomes, Holman "
                 "& Bernstein 2023, PSJ 4:66, median over sky)",
    "planetY_box": "SCT25 warp-producing range ~0.06-1 M_earth, "
                   "a=100-200 AU, i>~10 deg"},
    "rungs": {}}

for gname in GEOMS:
    gt = gname.split("-")[0]
    for a9 in A9_LADDER:
        key = f"{gt}_a{int(a9)}"
        dr = np.array([r[f"{key}_drot"] for r in rows])
        mr = np.array([r[f"{key}_mreq"] for r in rows])
        ok = np.isfinite(mr)
        bound = eph_bound_5sig(a9)
        res["rungs"][key] = {
            "geometry": gname, "a9_AU": a9,
            "med_drot": float(np.nanmedian(dr)),
            "m_req_median_in": float(np.nanmedian(mr[ok & inc])),
            "m_req_p05_in": float(np.nanpercentile(mr[ok & inc], 5)),
            "m_req_min_in": float(np.nanmin(mr[ok & inc])),
            "m_req_median_out": float(np.nanmedian(mr[ok & ~inc])),
            "frac_in_within_planetY_box": float(np.mean(
                (mr[ok & inc] >= 0.06) & (mr[ok & inc] <= 1.0))),
            "frac_in_below_eph_bound": float(np.mean(mr[ok & inc] < bound)),
            "eph_bound_5sig_earth": float(bound),
            "note": "frac_within_planetY_box: share of in-cap comets "
                    "whose required mass falls inside the SCT25 "
                    "0.06-1 M_earth box; frac_below_eph_bound: share "
                    "whose required mass would escape the Gomes+23 "
                    "5-sigma tidal detection line"}
        a = res["rungs"][key]
        logger.info(f"{gname:13s} a9={a9:5.0f} AU: med drot="
                    f"{a['med_drot']:.5f} deg | m_req in-cap med "
                    f"{a['m_req_median_in']:.0f} M_earth (min "
                    f"{a['m_req_min_in']:.0f}) | in-box "
                    f"{a['frac_in_within_planetY_box']:.2f} | "
                    f"<eph-bound {a['frac_in_below_eph_bound']:.2f}")

# ------------------------------------------------------------------
# Write
# ------------------------------------------------------------------

out = str(RESULTS / "step_b56_inner_perturber.json")
json.dump(res, open(out, "w"), indent=1, default=float)
csv_out = str(RESULTS / "step_b56_inner_perturber.csv")
with open(csv_out, "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    w.writeheader(); w.writerows(rows)
logger.data_save(out)
logger.data_save(csv_out)
# ------------------------------------------------------------------
# Figure
# ------------------------------------------------------------------

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(11.5, 4.6))

ax = axes[0]
dgrid = np.linspace(90, 270, 200)
ax.fill_between(dgrid, 0.06, 1.0, color="orange", alpha=0.12,
                label="SCT25 Planet-Y box (0.06-1 $M_\\oplus$)")
ax.plot(dgrid, [eph_bound_5sig(d) for d in dgrid], "b-", lw=1.4,
        label="ephemeris 5$\\sigma$ line (Gomes+23)")
for gname, col in (("anti-aligned", "crimson"), ("warp-plane", "darkgreen")):
    gt = gname.split("-")[0]
    med = [res["rungs"][f"{gt}_a{int(a)}"]["m_req_median_in"] for a in A9_LADDER]
    p05 = [res["rungs"][f"{gt}_a{int(a)}"]["m_req_p05_in"] for a in A9_LADDER]
    ax.plot(A9_LADDER, med, "o-", c=col, label=f"{gname} in-cap median")
    ax.plot(A9_LADDER, p05, "s--", c=col, alpha=0.45,
            label=f"{gname} in-cap 5th pct")
ax.axhline(318, color="steelblue", ls=":", lw=1.2, label="1 $M_{Jup}$")
ax.set_xscale("log"); ax.set_yscale("log")
ax.set_xlabel("inner-perturber semimajor axis $a_9$ (AU)")
ax.set_ylabel("required mass ($M_\\oplus$)")
ax.legend(frameon=False, fontsize=7)
ax.set_title("required point mass in the Planet-Y regime", fontsize=10)

ax = axes[1]
x = np.array(A9_LADDER)
for gname, col, off in (("anti-aligned", "crimson", -0.012),
                        ("warp-plane", "darkgreen", +0.012)):
    gt = gname.split("-")[0]
    fr = [res["rungs"][f"{gt}_a{int(a)}"]["frac_in_below_eph_bound"]
          for a in A9_LADDER]
    ax.bar(np.log10(x) + off, fr, width=0.022,
           color=col, edgecolor="k", lw=0.4, label=gname)
ax.set_xticks(np.log10(x)); ax.set_xticklabels([f"{int(a)}" for a in A9_LADDER])
ax.set_xlabel("$a_9$ (AU)"); ax.set_ylabel("fraction of in-cap comets")
ax.set_ylim(0, 1)
ax.set_title("share whose required mass escapes the\n5$\\sigma$ ephemeris line", fontsize=10)
ax.legend(frameon=False, fontsize=8)

fig.tight_layout()
FIG = RESULTS / "figures"; FIG.mkdir(exist_ok=True)
fig.savefig(FIG / "supplementary" / "step_b56_inner_perturber.png", dpi=300)
logger.data_save(FIG / 'supplementary' / 'step_b56_inner_perturber.png')