#!/usr/bin/env python3
"""Step 076 -- inner-region slip profile: where inside 60 AU does the
excess rotation develop?

Step 071 showed the in-cap rotation excess is already fully formed at
60 AU and flat outward to 400 AU.  This step resolves the inner
profile: the same bidirectional legs record the osculating barycentric
periapsis direction at shells 8-100 AU.  The ordinary orig/fut
discrepancy is generated by planetary encounters in the giant-planet
zone (~5-30 AU); if the in-cap excess develops on the same radial
profile it rides the encounter channel, while an excess already
present at 8-15 AU -- interior to the giant-planet lever arm -- points
to a pre-encounter (inbound-passage or observed-arc) origin.

Outputs:
    results/step_b41_inner_slip.json
    results/step_b41_inner_slip.csv      (per comet per shell)
    results/figures/step_b41_inner_slip.png
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from scripts.utils.tep9_common import DATA_RAW, RESULTS, tee_stdout
from scripts.utils.step_logger import StepLogger

logger = StepLogger("step_076_inner_slip_profile")
tee_stdout(logger)
logger.header("Inner-region slip profile: multi-shell legs 8-100 AU (REBOUND/DE440s)")

import csv
import json
import math
import re
import numpy as np
import rebound
import spiceypy as sp
from html.parser import HTMLParser
from scipy.stats import spearmanr

# ------------------------------------------------------------------
# CODE table parser (identical to step_063/071)
# ------------------------------------------------------------------

class TP(HTMLParser):
    def __init__(self):
        super().__init__(); self.rows = []; self.cur = []; self.buf = ""; self.in_td = False
    def handle_starttag(self, t, a):
        if t == "tr": self.cur = []
        elif t == "td": self.in_td = True; self.buf = ""
    def handle_endtag(self, t):
        if t == "td": self.in_td = False; self.cur.append(self.buf.strip())
        elif t == "tr" and self.cur: self.rows.append(self.cur)
    def handle_data(self, d):
        if self.in_td: self.buf += d

def parse_code(path):
    p = TP(); p.feed(open(path, encoding="utf-8", errors="replace").read())
    out = {}
    for r in p.rows:
        if len(r) < 14: continue
        try:
            out[r[0].strip()] = dict(desig=r[0].strip(),
                cls=re.sub(r"^\d", "", r[3].strip()),
                T=r[7].strip(),
                q=float(r[8]), e=float(r[9]), w=float(r[10]),
                Om=float(r[11]), i=float(r[12]), aa=float(r[13]))
        except (ValueError, IndexError):
            continue
    return out

def perih_dir(om, Om, inc):
    co, so, cO, sO, ci, si = np.cos(om), np.sin(om), np.cos(Om), np.sin(Om), np.cos(inc), np.sin(inc)
    return np.array([cO*co - sO*so*ci, sO*co + cO*so*ci, so*si])

def sep(a, b):
    return math.degrees(math.acos(np.clip(np.dot(a, b), -1, 1)))

def lv(l, b):
    l, b = math.radians(l), math.radians(b)
    return np.array([math.cos(b)*math.cos(l), math.cos(b)*math.sin(l), math.sin(b)])

TNO = lv(34, -13)
CAP = 60.0

# ------------------------------------------------------------------
# Ephemeris setup (identical to step_063/071)
# ------------------------------------------------------------------

SPK = DATA_RAW / "spice" / "de440s.bsp"
if not SPK.exists():
    raise FileNotFoundError(f"JPL ephemeris missing: {SPK}")
sp.furnsh(str(SPK))

AU_KM   = 149597870.7
DAY_YR  = 365.25
EPS     = math.radians(23.4392911)
RX      = np.array([[1, 0, 0],
                    [0, math.cos(EPS), math.sin(EPS)],
                    [0, -math.sin(EPS), math.cos(EPS)]])

GM_SUN = 1.32712440018e11
GM = {"1": 2.2031868551e4, "2": 3.2485859200e5, "3": 4.0350323562e5,
      "4": 4.2828375814e4, "5": 1.2671276480e8, "6": 3.7940626000e7,
      "7": 5.7945490100e6, "8": 6.8365271006e6, "9": 1.0868657e3}
PLANET_IDS = list(GM.keys())

def jd_tt(y, m, d):
    if m <= 2: y -= 1; m += 12
    A = y // 100; B = 2 - A + A // 4
    return int(365.25 * (y + 4716)) + int(30.6001 * (m + 1)) + d + B - 1524.5

def perihelion_et(T):
    m = re.match(r"(\d{4})\s+(\d{1,2})\s+(\d+\.?\d*)", T)
    if not m:
        return None
    return (jd_tt(int(m.group(1)), int(m.group(2)), float(m.group(3))) - 2451545.0) * 86400.0

def body_state(body, et):
    st, _ = sp.spkezr(body, et, "J2000", "NONE", "0")
    return RX @ np.array(st[:3]) / AU_KM, RX @ np.array(st[3:]) / AU_KM * 86400 * DAY_YR

# ------------------------------------------------------------------
# Inner-shell integration
# ------------------------------------------------------------------

MU = 4 * math.pi ** 2
SHELLS = [8.0, 12.0, 16.0, 20.0, 25.0, 30.0, 35.0, 40.0, 50.0,
          60.0, 80.0, 100.0]
R_MAX  = SHELLS[-1]
T_MAX  = 15000.0
DT_OUT = 0.25            # finer sampling near the encounter zone

def init_sim(et):
    sim = rebound.Simulation()
    sim.G = MU
    ps, vs = body_state("10", et)
    sim.add(x=ps[0], y=ps[1], z=ps[2], vx=vs[0], vy=vs[1], vz=vs[2], m=1.0)
    for b in PLANET_IDS:
        pp, vv = body_state(b, et)
        sim.add(x=pp[0], y=pp[1], z=pp[2], vx=vv[0], vy=vv[1], vz=vv[2],
                m=GM[b] / GM_SUN)
    return sim, ps, vs

def state_at_periapsis(ro):
    w_, O_, i_ = map(math.radians, (ro["w"], ro["Om"], ro["i"]))
    ph = perih_dir(w_, O_, i_)
    hh = np.array([math.sin(i_) * math.sin(O_), -math.sin(i_) * math.cos(O_), math.cos(i_)])
    th = np.cross(hh, ph); th /= np.linalg.norm(th)
    rvec = ro["q"] * ph
    vvec = math.sqrt(MU * (1 + ro["e"]) / ro["q"]) * th
    return rvec, vvec

def boundary_orbit(r_rel, v_rel, mtot):
    mu = MU * mtot
    r = np.linalg.norm(r_rel)
    h = np.cross(r_rel, v_rel)
    evec = (np.cross(v_rel, h) / mu) - r_rel / r
    en = np.linalg.norm(evec)
    phat = evec / en if en > 1e-12 else r_rel / r
    E = v_rel.dot(v_rel) / 2 - mu / r
    return phat, -2 * E / mu * 1e6, np.linalg.norm(h)

def integrate_leg(ro, et, direction):
    sim, ps, vs = init_sim(et)
    rvec, vvec = state_at_periapsis(ro)
    sim.add(x=rvec[0] + ps[0], y=rvec[1] + ps[1], z=rvec[2] + ps[2],
            vx=vvec[0] + vs[0], vy=vvec[1] + vs[1], vz=vvec[2] + vs[2])
    nc = sim.N - 1
    sim.integrator = "ias15"
    denc = np.full(sim.N - 1, np.inf)
    hits = {}
    nxt = 0
    t = direction * DT_OUT
    while abs(t) < T_MAX:
        sim.integrate(t, exact_finish_time=0)
        p = sim.particles
        r_rel = np.array([p[nc].x - p[0].x, p[nc].y - p[0].y, p[nc].z - p[0].z])
        rr = np.linalg.norm(r_rel)
        for j in range(1, sim.N - 1):
            d = math.sqrt((p[nc].x - p[j].x) ** 2 + (p[nc].y - p[j].y) ** 2 +
                          (p[nc].z - p[j].z) ** 2)
            if d < denc[j - 1]: denc[j - 1] = d
        if nxt < len(SHELLS) and rr >= SHELLS[nxt]:
            mtot = sum(pp.m for pp in sim.particles)
            rb = np.zeros(3); vb = np.zeros(3)
            for pp in sim.particles:
                rb += pp.m * np.array([pp.x, pp.y, pp.z])
                vb += pp.m * np.array([pp.vx, pp.vy, pp.vz])
            rb /= mtot; vb /= mtot
            r_b = np.array([p[nc].x, p[nc].y, p[nc].z]) - rb
            v_b = np.array([p[nc].vx, p[nc].vy, p[nc].vz]) - vb
            phat, aa, hh = boundary_orbit(r_b, v_b, mtot)
            while nxt < len(SHELLS) and rr >= SHELLS[nxt]:
                hits[SHELLS[nxt]] = (phat, hh, aa, float(t))
                nxt += 1
            if nxt >= len(SHELLS):
                break
        t += direction * DT_OUT
    if len(hits) < len(SHELLS):
        return None
    return dict(hits=hits, denc=float(denc.min()))

# ------------------------------------------------------------------
# Sample (identical to step_063/071)
# ------------------------------------------------------------------

osc  = parse_code(str(DATA_RAW / "code" / "code_osculating.html"))
orig = parse_code(str(DATA_RAW / "code" / "code_original.html"))
fut  = parse_code(str(DATA_RAW / "code" / "code_future.html"))
warsaw = {l[5:17].strip() for l in open(str(DATA_RAW / "warsaw" / "warsaw_tablec.dat")) if len(l) > 115}

sample = []
for k, ro in orig.items():
    if k not in fut: continue
    if not (0 < ro["aa"] < 100 and ro["cls"] in ("1a", "1a+", "1b")) or k in warsaw:
        continue
    if k not in osc: continue
    et = perihelion_et(osc[k]["T"])
    if et is None: continue
    sample.append((k, ro, osc[k], et))

logger.info(f"sample: {len(sample)} class-1 CODE comets; inner shells {SHELLS[0]:.0f}-{SHELLS[-1]:.0f} AU")

rows = []
failed = []
for idx, (k, ro, oo, et) in enumerate(sample):
    try:
        rb = integrate_leg(oo, et, -1)
        rf = integrate_leg(oo, et, +1)
    except Exception as e:
        failed.append(k); logger.warning(f"{k}: {e}"); continue
    if rb is None or rf is None:
        failed.append(k); logger.warning(f"{k}: outer shell not reached"); continue
    po = perih_dir(math.radians(ro["w"]), math.radians(ro["Om"]), math.radians(ro["i"]))
    rec = dict(desig=k, q=ro["q"], i=ro["i"],
               theta=sep(-po, TNO),
               denc=min(rb["denc"], rf["denc"]))
    for s in SHELLS:
        pb, hb, ab_, tb = rb["hits"][s]
        pf_, hf, af_, tf = rf["hits"][s]
        rec[f"drot_{int(s)}"] = sep(pb, pf_)
        rec[f"h_{int(s)}"] = 0.5 * (hb + hf)
    rows.append(rec)
    if (idx + 1) % 20 == 0:
        logger.info(f"  {idx+1}/{len(sample)}")

logger.info(f"integrated {len(rows)} comets x {len(SHELLS)} shells, {len(failed)} failures")

# ------------------------------------------------------------------
# Inner profile
# ------------------------------------------------------------------

th = np.array([r["theta"] for r in rows])
inc = th < CAP
rng = np.random.default_rng(20260918)
NB = 20000

prof = {"shells": SHELLS, "n_in": int(inc.sum()), "n_out": int((~inc).sum()),
        "median_drot_in": [], "median_drot_out": [],
        "excess_drot": [], "excess_ci": []}

for s in SHELLS:
    tag = int(s)
    dr = np.array([r[f"drot_{tag}"] for r in rows])
    prof["median_drot_in"].append(float(np.median(dr[inc])))
    prof["median_drot_out"].append(float(np.median(dr[~inc])))
    ex = dr[inc] - np.median(dr[~inc])
    prof["excess_drot"].append(float(np.median(ex)))
    if inc.sum() >= 5:
        idx = rng.integers(0, int(inc.sum()), (NB, int(inc.sum())))
        bs = np.median((dr[inc] - np.median(dr[~inc]))[idx], axis=1)
        prof["excess_ci"].append([float(x) for x in np.percentile(bs, [16, 84])])
    else:
        prof["excess_ci"].append([np.nan, np.nan])

# where does the excess reach half its 100-AU value? (developed radius)
ex = np.array(prof["excess_drot"])
final = ex[-1]
half = None
for j, s in enumerate(SHELLS):
    if ex[j] >= 0.5 * final:
        half = s; break
prof["excess_half_radius_au"] = half

# correlation of excess with radius across the inner shells (is the
# excess growing through the encounter zone or already present?)
rho, p = spearmanr(SHELLS, ex)
prof["excess_vs_shell"] = {"rho": float(rho), "p_2sided": float(p)}

res = {
    "method": "step_071 machinery restricted to inner shells 8-100 AU "
              "(DT=0.25 yr).  Median inbound/outbound rotation and "
              "in-cap excess per shell; the radius where the excess "
              "reaches half its 100 AU value localizes its origin "
              "relative to the giant-planet encounter zone (~5-30 AU).",
    "cap_deg": CAP, "axis": "34,-13", "seed": 20260918,
    "n": len(rows), "n_failed": len(failed), "failed": failed,
    "profile": prof,
}

fields = ["desig", "q", "i", "theta", "denc"] + \
         [f"drot_{int(s)}" for s in SHELLS] + [f"h_{int(s)}" for s in SHELLS]
with open(RESULTS / "step_b41_inner_slip.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=fields); w.writeheader()
    for r in rows: w.writerow(r)

with open(RESULTS / "step_b41_inner_slip.json", "w") as f:
    json.dump(res, f, indent=1)
print(f"wrote {RESULTS / 'step_b41_inner_slip.json'}")
print(f"wrote {RESULTS / 'step_b41_inner_slip.csv'}")

# ------------------------------------------------------------------
# Figure
# ------------------------------------------------------------------

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(11, 4.4))

ax = axes[0]
ax.plot(SHELLS, prof["median_drot_in"], "o-", color="crimson",
        label=f"inside cap ($n={int(inc.sum())}$)")
ax.plot(SHELLS, prof["median_drot_out"], "o-", color="0.55",
        label=f"outside ($n={int((~inc).sum())}$)")
ax.axvspan(5, 30, color="0.9", alpha=0.5, label="giant-planet zone")
ax.set_xlabel("shell radius $s$ (AU)")
ax.set_ylabel(r"median $\delta\theta(s)$ (deg)")
ax.legend(frameon=False, fontsize=8)
ax.set_title("rotation profile inside 100 AU", fontsize=10)

ax = axes[1]
ci = np.array(prof["excess_ci"])
ax.fill_between(SHELLS, ci[:, 0], ci[:, 1], color="crimson", alpha=0.15)
ax.plot(SHELLS, ex, "o-", color="crimson")
ax.axhline(0, color="k", ls=":", lw=1)
ax.axvspan(5, 30, color="0.9", alpha=0.5)
if half:
    ax.axvline(half, color="k", ls="--", lw=1,
               label=f"half-excess at {half:.0f} AU")
    ax.legend(frameon=False, fontsize=8)
ax.set_xlabel("shell radius $s$ (AU)")
ax.set_ylabel(r"in-cap excess $\delta\theta$ (deg)")
ax.set_title("where the excess develops", fontsize=10)

fig.tight_layout()
FIG = RESULTS / "figures"; FIG.mkdir(exist_ok=True)
fig.savefig(FIG / "step_b41_inner_slip.png", dpi=150)
print(f"wrote {FIG / 'step_b41_inner_slip.png'}")

for j, s in enumerate(SHELLS):
    logger.info(f"s={s:6.1f} AU  drot in/out = {prof['median_drot_in'][j]:.4f}/"
                f"{prof['median_drot_out'][j]:.4f} deg  excess = "
                f"{prof['excess_drot'][j]:+.4f} deg")
logger.info(f"half-excess radius: {half} AU")
